name: expense_tracker_smart_ai
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  uuid: ^4.1.0
  js: ^0.6.7
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  fl_chart: ^0.68.0  # Add this for charts
  http: ^1.1.0       # Add this for API calls

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true  # This line is CRUCIAL!