name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v3

      - name: Remove old Flutter SDK (optional safety)
        run: rm -rf "$HOME/.flutter"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'
          channel: 'stable'
          cache: false
          architecture: x64

      - name: Check Flutter & Dart version
        run: flutter --version

      - name: Get dependencies
        run: flutter pub get

      - name: Clean build
        run: flutter clean

      - name: Build web
        run: flutter build web --base-href /expense_tracker_smart_ai/

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build/web'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
